/**
 * Auto-generated Supabase TypeScript types.
 *
 * Regenerate with:
 *   npm run gen:types
 *
 * Do NOT edit this file by hand — changes will be overwritten on next generation.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      audit_logs: {
        Row: {
          created_at: string
          event: string
          id: string
          metadata: Json | null
          user_id: string | null
        }
        Insert: {
          created_at?: string
          event: string
          id?: string
          metadata?: Json | null
          user_id?: string | null
        }
        Update: {
          created_at?: string
          event?: string
          id?: string
          metadata?: Json | null
          user_id?: string | null
        }
        Relationships: []
      }
      friendships: {
        Row: {
          created_at: string
          deleted_at: string | null
          id: string
          recipient_id: string
          requester_id: string
          status: Database["public"]["Enums"]["friendship_status"]
        }
        Insert: {
          created_at?: string
          deleted_at?: string | null
          id?: string
          recipient_id: string
          requester_id: string
          status?: Database["public"]["Enums"]["friendship_status"]
        }
        Update: {
          created_at?: string
          deleted_at?: string | null
          id?: string
          recipient_id?: string
          requester_id?: string
          status?: Database["public"]["Enums"]["friendship_status"]
        }
        Relationships: [
          {
            foreignKeyName: "friendships_recipient_id_fkey"
            columns: ["recipient_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "friendships_requester_id_fkey"
            columns: ["requester_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      invite_links: {
        Row: {
          created_at: string
          created_by: string
          expires_at: string | null
          id: string
          moment_id: string
          token: string
        }
        Insert: {
          created_at?: string
          created_by: string
          expires_at?: string | null
          id?: string
          moment_id: string
          token?: string
        }
        Update: {
          created_at?: string
          created_by?: string
          expires_at?: string | null
          id?: string
          moment_id?: string
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "invite_links_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invite_links_moment_id_fkey"
            columns: ["moment_id"]
            isOneToOne: false
            referencedRelation: "moments"
            referencedColumns: ["id"]
          },
        ]
      }
      moment_archive: {
        Row: {
          archived_at: string
          id: string
          moment_id: string
          user_id: string
        }
        Insert: {
          archived_at?: string
          id?: string
          moment_id: string
          user_id: string
        }
        Update: {
          archived_at?: string
          id?: string
          moment_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "moment_archive_moment_id_fkey"
            columns: ["moment_id"]
            isOneToOne: false
            referencedRelation: "moments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "moment_archive_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      moment_members: {
        Row: {
          created_at: string
          id: string
          invited_by: string
          invited_email: string | null
          moment_id: string
          role: Database["public"]["Enums"]["moment_member_role"]
          status: Database["public"]["Enums"]["moment_member_status"]
          user_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          invited_by: string
          invited_email?: string | null
          moment_id: string
          role?: Database["public"]["Enums"]["moment_member_role"]
          status?: Database["public"]["Enums"]["moment_member_status"]
          user_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          invited_by?: string
          invited_email?: string | null
          moment_id?: string
          role?: Database["public"]["Enums"]["moment_member_role"]
          status?: Database["public"]["Enums"]["moment_member_status"]
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "moment_members_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "moment_members_moment_id_fkey"
            columns: ["moment_id"]
            isOneToOne: false
            referencedRelation: "moments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "moment_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      moment_tags: {
        Row: {
          created_at: string
          created_by: string
          id: string
          moment_id: string
          tag: string
        }
        Insert: {
          created_at?: string
          created_by: string
          id?: string
          moment_id: string
          tag: string
        }
        Update: {
          created_at?: string
          created_by?: string
          id?: string
          moment_id?: string
          tag?: string
        }
        Relationships: [
          {
            foreignKeyName: "moment_tags_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "moment_tags_moment_id_fkey"
            columns: ["moment_id"]
            isOneToOne: false
            referencedRelation: "moments"
            referencedColumns: ["id"]
          },
        ]
      }
      moments: {
        Row: {
          cover_photo_url: string | null
          created_at: string
          date_day: number | null
          date_month: number | null
          date_year: number | null
          id: string
          location: string | null
          name: string
          owner_id: string
        }
        Insert: {
          cover_photo_url?: string | null
          created_at?: string
          date_day?: number | null
          date_month?: number | null
          date_year?: number | null
          id?: string
          location?: string | null
          name: string
          owner_id: string
        }
        Update: {
          cover_photo_url?: string | null
          created_at?: string
          date_day?: number | null
          date_month?: number | null
          date_year?: number | null
          id?: string
          location?: string | null
          name?: string
          owner_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "moments_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_preferences: {
        Row: {
          archived_moment_notifications: boolean
          friend_request_accepted: boolean
          friend_request_received: boolean
          id: string
          member_left: boolean
          moment_invite: boolean
          moment_invite_response: boolean
          new_post: boolean
          ownership_transferred: boolean
          reminder_cadence: Database["public"]["Enums"]["reminder_cadence"]
          user_id: string
        }
        Insert: {
          archived_moment_notifications?: boolean
          friend_request_accepted?: boolean
          friend_request_received?: boolean
          id?: string
          member_left?: boolean
          moment_invite?: boolean
          moment_invite_response?: boolean
          new_post?: boolean
          ownership_transferred?: boolean
          reminder_cadence?: Database["public"]["Enums"]["reminder_cadence"]
          user_id: string
        }
        Update: {
          archived_moment_notifications?: boolean
          friend_request_accepted?: boolean
          friend_request_received?: boolean
          id?: string
          member_left?: boolean
          moment_invite?: boolean
          moment_invite_response?: boolean
          new_post?: boolean
          ownership_transferred?: boolean
          reminder_cadence?: Database["public"]["Enums"]["reminder_cadence"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notification_preferences_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          created_at: string
          id: string
          invite_role: string | null
          metadata: Json | null
          moment_id: string | null
          post_id: string | null
          read: boolean
          related_moment_id: string | null
          related_user_id: string | null
          type: Database["public"]["Enums"]["notification_type"]
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          invite_role?: string | null
          metadata?: Json | null
          moment_id?: string | null
          post_id?: string | null
          read?: boolean
          related_moment_id?: string | null
          related_user_id?: string | null
          type: Database["public"]["Enums"]["notification_type"]
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          invite_role?: string | null
          metadata?: Json | null
          moment_id?: string | null
          post_id?: string | null
          read?: boolean
          related_moment_id?: string | null
          related_user_id?: string | null
          type?: Database["public"]["Enums"]["notification_type"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_moment_id_fkey"
            columns: ["moment_id"]
            isOneToOne: false
            referencedRelation: "moments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_related_moment_id_fkey"
            columns: ["related_moment_id"]
            isOneToOne: false
            referencedRelation: "moments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_related_user_id_fkey"
            columns: ["related_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      pending_moment_invites: {
        Row: {
          created_at: string
          email: string
          id: string
          invited_by: string
          moment_id: string
          redeemed_at: string | null
          role: string
          token: string
        }
        Insert: {
          created_at?: string
          email: string
          id?: string
          invited_by: string
          moment_id: string
          redeemed_at?: string | null
          role?: string
          token?: string
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          invited_by?: string
          moment_id?: string
          redeemed_at?: string | null
          role?: string
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "pending_moment_invites_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pending_moment_invites_moment_id_fkey"
            columns: ["moment_id"]
            isOneToOne: false
            referencedRelation: "moments"
            referencedColumns: ["id"]
          },
        ]
      }
      post_media: {
        Row: {
          created_at: string
          deleted_at: string | null
          id: string
          media_type: Database["public"]["Enums"]["media_type"]
          post_id: string
          storage_url: string
        }
        Insert: {
          created_at?: string
          deleted_at?: string | null
          id?: string
          media_type: Database["public"]["Enums"]["media_type"]
          post_id: string
          storage_url: string
        }
        Update: {
          created_at?: string
          deleted_at?: string | null
          id?: string
          media_type?: Database["public"]["Enums"]["media_type"]
          post_id?: string
          storage_url?: string
        }
        Relationships: [
          {
            foreignKeyName: "post_media_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "posts"
            referencedColumns: ["id"]
          },
        ]
      }
      posts: {
        Row: {
          author_id: string
          content: string | null
          created_at: string
          deleted_at: string | null
          edited_at: string | null
          id: string
          moment_id: string
        }
        Insert: {
          author_id: string
          content?: string | null
          created_at?: string
          deleted_at?: string | null
          edited_at?: string | null
          id?: string
          moment_id: string
        }
        Update: {
          author_id?: string
          content?: string | null
          created_at?: string
          deleted_at?: string | null
          edited_at?: string | null
          id?: string
          moment_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "posts_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "posts_moment_id_fkey"
            columns: ["moment_id"]
            isOneToOne: false
            referencedRelation: "moments"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          created_at: string
          email: string
          first_name: string
          id: string
          last_name: string
          profile_photo_url: string | null
          username: string
        }
        Insert: {
          created_at?: string
          email: string
          first_name: string
          id: string
          last_name: string
          profile_photo_url?: string | null
          username: string
        }
        Update: {
          created_at?: string
          email?: string
          first_name?: string
          id?: string
          last_name?: string
          profile_photo_url?: string | null
          username?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      check_email_available: { Args: { p_email: string }; Returns: boolean }
      check_username_available: {
        Args: { p_username: string }
        Returns: boolean
      }
      is_moment_editor: {
        Args: { p_moment_id: string; p_user_id: string }
        Returns: boolean
      }
      is_moment_member: {
        Args: { p_moment_id: string; p_user_id: string }
        Returns: boolean
      }
      transfer_moment_ownership: {
        Args: {
          p_current_user_id: string
          p_moment_id: string
          p_new_owner_id: string
        }
        Returns: undefined
      }
    }
    Enums: {
      friendship_status: "pending" | "accepted" | "declined"
      media_type: "photo" | "video" | "audio"
      moment_member_role: "editor" | "reader"
      moment_member_status: "pending" | "accepted" | "declined"
      notification_type:
        | "friend_request_received"
        | "friend_request_accepted"
        | "moment_invite"
        | "moment_invite_response"
        | "new_post"
        | "member_left"
        | "ownership_transferred"
        | "moment_invite_accepted"
        | "moment_invite_declined"
        | "reminder"
        | "role_changed"
        | "moment_deleted"
        | "ownership_transferred_away"
      reminder_cadence: "weekly" | "biweekly" | "monthly" | "never"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      friendship_status: ["pending", "accepted", "declined"],
      media_type: ["photo", "video", "audio"],
      moment_member_role: ["editor", "reader"],
      moment_member_status: ["pending", "accepted", "declined"],
      notification_type: [
        "friend_request_received",
        "friend_request_accepted",
        "moment_invite",
        "moment_invite_response",
        "new_post",
        "member_left",
        "ownership_transferred",
        "moment_invite_accepted",
        "moment_invite_declined",
        "reminder",
        "role_changed",
        "moment_deleted",
        "ownership_transferred_away",
      ],
      reminder_cadence: ["weekly", "biweekly", "monthly", "never"],
    },
  },
} as const
